[package]
cairo-version = "2.2.0"
name = "rollyourown"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
cubit = {git = "https://github.com/influenceth/cubit.git"}
# dojo = {git = "https://github.com/dojoengine/dojo.git"}
# dojo = {git = "https://github.com/dojoengine/dojo.git", rev = "d7f46502cba3d6462b68a4dfb07336377bca2678"}
dojo = {git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.1"}


[[target.dojo]]

[scripts]
build = "sozo build && scarb run gendojo"
gendojo = "./scripts/gen.sh"
auth = "./scripts/default_auth.sh local"
migrate = "sozo migrate && scarb run gendojo && scarb run auth"
migrate_dev = "sozo migrate --rpc-url https://api.cartridge.gg/x/ryo1/katana --account-address 0x41d017913d81b1a6b476a3a59122a82fdd64fde2010c79ff3dfd151544a2450 --private-key 0x1dd41713d8e369fb26850ac2e399ebe5932764ce62dc8a8e5b0d46fb360dcf3"

[tool.dojo.env]
# Katana
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
rpc_url = "http://localhost:5050"

# account_address = "0x41d017913d81b1a6b476a3a59122a82fdd64fde2010c79ff3dfd151544a2450"
# private_key = "0x1dd41713d8e369fb26850ac2e399ebe5932764ce62dc8a8e5b0d46fb360dcf3"
# rpc_url = "https://api.cartridge.gg/x/ryo1/katana"

[tool.dojo.world]
name = "Roll Your Own"
description = "example world"
website = "https://rollyourown.preview.cartridge.gg/"
icon_uri = "file://assets/icon.png"
cover_uri = "file://assets/cover.png"
socials.x = "https://x.com/TheDopeWars"